import type { ResumeData, Template, TemplateConfig, Customization } from './types';

export const DEFAULT_PERSONAL_INFO = {
  fullName: '',
  jobTitle: '',
  email: '',
  phone: '',
  location: '',
  website: '',
  linkedin: '',
  github: '',
  summary: '',
  photo: '',
};

export const DEFAULT_RESUME_DATA: ResumeData = {
  personal: DEFAULT_PERSONAL_INFO,
  experience: [],
  education: [],
  projects: [],
  skills: [],
  languages: [],
  certificates: [],
  achievements: [],
  volunteerWork: [],
  references: [],
  customSections: [],
  sectionOrder: [
    'personal',
    'summary',
    'experience',
    'education',
    'projects',
    'skills',
    'languages',
    'certificates',
    'achievements',
    'volunteerWork',
    'references',
  ],
  sectionVisibility: {
    personal: true,
    summary: true,
    experience: true,
    education: true,
    projects: true,
    skills: true,
    languages: true,
    certificates: true,
    achievements: true,
    volunteerWork: true,
    references: true,
  },
};

export const DEFAULT_CUSTOMIZATION: Customization = {
  accentColor: '#10b981',
  fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  headingFontFamily: 'Inter, system-ui, -apple-system, sans-serif',
  fontSize: 10.5,
  lineHeight: 1.55,
  sectionSpacing: 16,
  margin: 48,
  headerStyle: 'centered',
  iconStyle: 'line',
  dividerStyle: 'line',
  borderRadius: 6,
  columns: 1,
  pageSize: 'a4',
  photoEnabled: false,
  theme: 'light',
};

export const TEMPLATES: Template[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    category: 'minimal',
    preview: 'minimal',
    config: {
      fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      headingFontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      fontSize: 10.5,
      lineHeight: 1.6,
      accentColor: '#10b981',
      secondaryColor: '#64748b',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      headingColor: '#0f172a',
      sectionSpacing: 16,
      margin: 48,
      headerStyle: 'centered',
      iconStyle: 'line',
      dividerStyle: 'line',
      borderRadius: 0,
      columns: 1,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'education',
        'projects',
        'skills',
        'languages',
        'certificates',
        'achievements',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'corporate',
    name: 'Corporate',
    category: 'corporate',
    preview: 'corporate',
    config: {
      fontFamily: 'Calibri, Arial, sans-serif',
      headingFontFamily: 'Calibri, Arial, sans-serif',
      fontSize: 11,
      lineHeight: 1.5,
      accentColor: '#1e40af',
      secondaryColor: '#475569',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      headingColor: '#0f172a',
      sectionSpacing: 18,
      margin: 54,
      headerStyle: 'left',
      iconStyle: 'filled',
      dividerStyle: 'double',
      borderRadius: 0,
      columns: 1,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'education',
        'skills',
        'certificates',
        'projects',
        'languages',
        'achievements',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'creative',
    name: 'Creative',
    category: 'creative',
    preview: 'creative',
    config: {
      fontFamily: 'Nunito, system-ui, sans-serif',
      headingFontFamily: 'Poppins, system-ui, sans-serif',
      fontSize: 10.5,
      lineHeight: 1.6,
      accentColor: '#7c3aed',
      secondaryColor: '#a855f7',
      backgroundColor: '#fafafa',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 20,
      margin: 40,
      headerStyle: 'split',
      iconStyle: 'filled',
      dividerStyle: 'dots',
      borderRadius: 12,
      columns: 2,
      photoEnabled: true,
      photoPosition: 'left',
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'projects',
        'skills',
        'education',
        'certificates',
        'languages',
        'achievements',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'executive',
    name: 'Executive',
    category: 'executive',
    preview: 'executive',
    config: {
      fontFamily: 'Georgia, serif',
      headingFontFamily: 'Merriweather, serif',
      fontSize: 11,
      lineHeight: 1.55,
      accentColor: '#1f2937',
      secondaryColor: '#6b7280',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 20,
      margin: 60,
      headerStyle: 'centered',
      iconStyle: 'none',
      dividerStyle: 'line',
      borderRadius: 0,
      columns: 1,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'education',
        'achievements',
        'certificates',
        'skills',
        'projects',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'developer',
    name: 'Developer',
    category: 'developer',
    preview: 'developer',
    config: {
      fontFamily: 'JetBrains Mono, Fira Code, monospace',
      headingFontFamily: 'Space Grotesk, system-ui, sans-serif',
      fontSize: 10,
      lineHeight: 1.6,
      accentColor: '#0891b2',
      secondaryColor: '#0e7490',
      backgroundColor: '#0f172a',
      textColor: '#e2e8f0',
      headingColor: '#f8fafc',
      sectionSpacing: 16,
      margin: 48,
      headerStyle: 'left',
      iconStyle: 'line',
      dividerStyle: 'line',
      borderRadius: 8,
      columns: 2,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'skills',
        'experience',
        'projects',
        'education',
        'certificates',
        'languages',
        'achievements',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'student',
    name: 'Student',
    category: 'student',
    preview: 'student',
    config: {
      fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      headingFontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      fontSize: 10.5,
      lineHeight: 1.55,
      accentColor: '#2563eb',
      secondaryColor: '#3b82f6',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      headingColor: '#0f172a',
      sectionSpacing: 14,
      margin: 48,
      headerStyle: 'centered',
      iconStyle: 'line',
      dividerStyle: 'line',
      borderRadius: 4,
      columns: 1,
      photoEnabled: true,
      photoPosition: 'top',
      sectionOrder: [
        'personal',
        'education',
        'summary',
        'projects',
        'experience',
        'skills',
        'certificates',
        'achievements',
        'volunteerWork',
        'languages',
        'references',
      ],
    },
  },
  {
    id: 'modern',
    name: 'Modern',
    category: 'modern',
    preview: 'modern',
    config: {
      fontFamily: 'DM Sans, system-ui, sans-serif',
      headingFontFamily: 'DM Sans, system-ui, sans-serif',
      fontSize: 10,
      lineHeight: 1.6,
      accentColor: '#0f172a',
      secondaryColor: '#334155',
      backgroundColor: '#ffffff',
      textColor: '#1e293b',
      headingColor: '#0f172a',
      sectionSpacing: 18,
      margin: 40,
      headerStyle: 'split',
      iconStyle: 'line',
      dividerStyle: 'none',
      borderRadius: 8,
      columns: 2,
      photoEnabled: true,
      photoPosition: 'right',
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'skills',
        'projects',
        'education',
        'certificates',
        'languages',
        'achievements',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'elegant',
    name: 'Elegant',
    category: 'elegant',
    preview: 'elegant',
    config: {
      fontFamily: 'Cormorant Garamond, Georgia, serif',
      headingFontFamily: 'Playfair Display, serif',
      fontSize: 11,
      lineHeight: 1.65,
      accentColor: '#92400e',
      secondaryColor: '#b45309',
      backgroundColor: '#fefce8',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 22,
      margin: 54,
      headerStyle: 'centered',
      iconStyle: 'line',
      dividerStyle: 'dots',
      borderRadius: 0,
      columns: 1,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'education',
        'skills',
        'projects',
        'certificates',
        'languages',
        'achievements',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'compact',
    name: 'Compact',
    category: 'compact',
    preview: 'compact',
    config: {
      fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      headingFontFamily: 'Inter, system-ui, -apple-system, sans-serif',
      fontSize: 9.5,
      lineHeight: 1.45,
      accentColor: '#374151',
      secondaryColor: '#6b7280',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 10,
      margin: 36,
      headerStyle: 'left',
      iconStyle: 'none',
      dividerStyle: 'line',
      borderRadius: 0,
      columns: 2,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'education',
        'skills',
        'projects',
        'certificates',
        'languages',
      ],
    },
  },
  {
    id: 'designer',
    name: 'Designer',
    category: 'designer',
    preview: 'designer',
    config: {
      fontFamily: 'Outfit, system-ui, sans-serif',
      headingFontFamily: 'Space Grotesk, system-ui, sans-serif',
      fontSize: 10,
      lineHeight: 1.6,
      accentColor: '#ec4899',
      secondaryColor: '#f43f5e',
      backgroundColor: '#fdf2f8',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 18,
      margin: 40,
      headerStyle: 'split',
      iconStyle: 'filled',
      dividerStyle: 'dots',
      borderRadius: 16,
      columns: 2,
      photoEnabled: true,
      photoPosition: 'left',
      sectionOrder: [
        'personal',
        'summary',
        'projects',
        'skills',
        'experience',
        'education',
        'certificates',
        'achievements',
        'languages',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'marketing',
    name: 'Marketing',
    category: 'marketing',
    preview: 'marketing',
    config: {
      fontFamily: 'Plus Jakarta Sans, system-ui, sans-serif',
      headingFontFamily: 'Plus Jakarta Sans, system-ui, sans-serif',
      fontSize: 10.5,
      lineHeight: 1.55,
      accentColor: '#c2410c',
      secondaryColor: '#ea580c',
      backgroundColor: '#fff7ed',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 16,
      margin: 48,
      headerStyle: 'left',
      iconStyle: 'filled',
      dividerStyle: 'line',
      borderRadius: 8,
      columns: 1,
      photoEnabled: true,
      photoPosition: 'right',
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'achievements',
        'skills',
        'projects',
        'education',
        'certificates',
        'languages',
        'volunteerWork',
        'references',
      ],
    },
  },
  {
    id: 'ats',
    name: 'ATS Optimized',
    category: 'ats',
    preview: 'ats',
    config: {
      fontFamily: 'Arial, Helvetica, sans-serif',
      headingFontFamily: 'Arial, Helvetica, sans-serif',
      fontSize: 11,
      lineHeight: 1.5,
      accentColor: '#1f2937',
      secondaryColor: '#4b5563',
      backgroundColor: '#ffffff',
      textColor: '#1f2937',
      headingColor: '#111827',
      sectionSpacing: 16,
      margin: 54,
      headerStyle: 'left',
      iconStyle: 'none',
      dividerStyle: 'line',
      borderRadius: 0,
      columns: 1,
      photoEnabled: false,
      sectionOrder: [
        'personal',
        'summary',
        'experience',
        'education',
        'skills',
        'certificates',
        'projects',
        'languages',
        'volunteerWork',
        'references',
      ],
    },
  },
];

export const FONT_OPTIONS = [
  { value: 'Inter, system-ui, -apple-system, sans-serif', label: 'Inter (Modern Sans)' },
  { value: 'DM Sans, system-ui, sans-serif', label: 'DM Sans (Clean)' },
  { value: 'Plus Jakarta Sans, system-ui, sans-serif', label: 'Plus Jakarta Sans (Contemporary)' },
  { value: 'Outfit, system-ui, sans-serif', label: 'Outfit (Geometric)' },
  { value: 'Space Grotesk, system-ui, sans-serif', label: 'Space Grotesk (Technical)' },
  { value: 'Nunito, system-ui, sans-serif', label: 'Nunito (Friendly)' },
  { value: 'Poppins, system-ui, sans-serif', label: 'Poppins (Geometric)' },
  { value: 'Calibri, Arial, sans-serif', label: 'Calibri (Corporate Standard)' },
  { value: 'Arial, Helvetica, sans-serif', label: 'Arial (Universal)' },
  { value: 'Helvetica, Arial, sans-serif', label: 'Helvetica (Classic)' },
  { value: 'Georgia, serif', label: 'Georgia (Readable Serif)' },
  { value: 'Merriweather, serif', label: 'Merriweather (Elegant Serif)' },
  { value: 'Playfair Display, serif', label: 'Playfair Display (High Contrast)' },
  { value: 'Cormorant Garamond, Georgia, serif', label: 'Cormorant Garamond (Classic)' },
  { value: 'JetBrains Mono, Fira Code, monospace', label: 'JetBrains Mono (Developer)' },
  { value: 'Fira Code, monospace', label: 'Fira Code (Code Ligatures)' },
];

export const HEADING_FONT_OPTIONS = [
  { value: 'Inter, system-ui, -apple-system, sans-serif', label: 'Inter' },
  { value: 'DM Sans, system-ui, sans-serif', label: 'DM Sans' },
  { value: 'Plus Jakarta Sans, system-ui, sans-serif', label: 'Plus Jakarta Sans' },
  { value: 'Outfit, system-ui, sans-serif', label: 'Outfit' },
  { value: 'Space Grotesk, system-ui, sans-serif', label: 'Space Grotesk' },
  { value: 'Poppins, system-ui, sans-serif', label: 'Poppins' },
  { value: 'Merriweather, serif', label: 'Merriweather' },
  { value: 'Playfair Display, serif', label: 'Playfair Display' },
  { value: 'Cormorant Garamond, Georgia, serif', label: 'Cormorant Garamond' },
];

export const HEADER_STYLES = [
  { value: 'centered', label: 'Centered', icon: '⬛' },
  { value: 'left', label: 'Left Aligned', icon: '◼️' },
  { value: 'split', label: 'Split (Name | Contact)', icon: '⬜⬛' },
  { value: 'stacked', label: 'Stacked Vertical', icon: '⬛\n⬛' },
  { value: 'sidebar', label: 'Sidebar Layout', icon: '⬛⬜' },
];

export const ICON_STYLES = [
  { value: 'line', label: 'Outline', icon: '○' },
  { value: 'filled', label: 'Filled', icon: '●' },
  { value: 'none', label: 'None', icon: '—' },
];

export const DIVIDER_STYLES = [
  { value: 'line', label: 'Solid Line', icon: '━' },
  { value: 'dots', label: 'Dotted', icon: '⋯' },
  { value: 'double', label: 'Double Line', icon: '═' },
  { value: 'none', label: 'None', icon: ' ' },
];

export const PAGE_SIZES = [
  { value: 'a4', label: 'A4 (210 × 297 mm)', dimensions: { width: 595.28, height: 841.89 } },
  { value: 'letter', label: 'US Letter (8.5 × 11 in)', dimensions: { width: 612, height: 792 } },
  { value: 'legal', label: 'US Legal (8.5 × 14 in)', dimensions: { width: 612, height: 1008 } },
];

export const SKILL_LEVELS = ['Beginner', 'Intermediate', 'Advanced', 'Expert'] as const;

export const LANGUAGE_PROFICIENCIES = ['Native', 'Fluent', 'Professional', 'Conversational', 'Basic'] as const;

export const SECTION_DEFINITIONS = [
  { id: 'personal', label: 'Personal Information', icon: '👤', required: true, description: 'Name, contact details, links' },
  { id: 'summary', label: 'Professional Summary', icon: '📝', required: false, description: '2-3 line career overview' },
  { id: 'experience', label: 'Work Experience', icon: '💼', required: false, description: 'Jobs, internships, roles' },
  { id: 'education', label: 'Education', icon: '🎓', required: false, description: 'Degrees, certifications, courses' },
  { id: 'projects', label: 'Projects', icon: '🚀', required: false, description: 'Personal, academic, freelance' },
  { id: 'skills', label: 'Skills', icon: '⚡', required: false, description: 'Technical, soft, languages' },
  { id: 'languages', label: 'Languages', icon: '🌐', required: false, description: 'Spoken/written languages' },
  { id: 'certificates', label: 'Certificates', icon: '📜', required: false, description: 'Professional certifications' },
  { id: 'achievements', label: 'Achievements', icon: '🏆', required: false, description: 'Awards, honors, publications' },
  { id: 'volunteerWork', label: 'Volunteer Work', icon: '🤝', required: false, description: 'Community, non-profit roles' },
  { id: 'references', label: 'References', icon: '👥', required: false, description: 'Professional references' },
] as const;

export function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

export function createEmptyExperience(): Experience {
  return {
    id: generateId(),
    company: '',
    position: '',
    location: '',
    startDate: '',
    endDate: '',
    current: false,
    description: '',
  };
}

export function createEmptyEducation(): Education {
  return {
    id: generateId(),
    institution: '',
    degree: '',
    field: '',
    location: '',
    startDate: '',
    endDate: '',
    current: false,
    gpa: '',
    description: '',
  };
}

export function createEmptyProject(): Project {
  return {
    id: generateId(),
    name: '',
    description: '',
    technologies: '',
    url: '',
    startDate: '',
    endDate: '',
  };
}

export function createEmptySkill(): Skill {
  return {
    id: generateId(),
    name: '',
    level: 'Intermediate',
    category: '',
  };
}

export function createEmptyLanguage(): Language {
  return {
    id: generateId(),
    name: '',
    proficiency: 'Professional',
  };
}

export function createEmptyCertificate(): Certificate {
  return {
    id: generateId(),
    name: '',
    issuer: '',
    date: '',
    url: '',
    description: '',
  };
}

export function createEmptyAchievement(): Achievement {
  return {
    id: generateId(),
    title: '',
    description: '',
    date: '',
  };
}

export function createEmptyVolunteerWork(): VolunteerWork {
  return {
    id: generateId(),
    organization: '',
    role: '',
    startDate: '',
    endDate: '',
    current: false,
    description: '',
  };
}

export function createEmptyReference(): Reference {
  return {
    id: generateId(),
    name: '',
    title: '',
    company: '',
    email: '',
    phone: '',
    relationship: '',
  };
}

export function createEmptyCustomSection(): CustomSection {
  return {
    id: generateId(),
    title: 'Custom Section',
    items: [],
  };
}

export function createEmptyCustomSectionItem(): CustomSectionItem {
  return {
    id: generateId(),
    title: '',
    subtitle: '',
    date: '',
    description: '',
  };
}